version: '3'

# run tests:  docker-compose up --build --force-recreate
# manual:  docker-compose run logstash bash
services:

  logstash:
    build:
      context: ../../
      dockerfile: ci/unit/Dockerfile
      args:
        - ELASTIC_STACK_VERSION=$ELASTIC_STACK_VERSION
    command: /usr/share/plugins/this/ci/unit/docker-compose-command.sh
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      LOGSTASH_SOURCE: 1
      JARS_SKIP: "true"
      OSS: "true"

